name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Multi commands
        run: |
          echo "First command!"
          echo "Second command!"
      - name: Print goodbye
        run: echo "Goodbye World!"
